### PR TITLE
add test_x_is_y tests from git

### PR DESCRIPTION
**Pull request by anarcat**

### CODE REVIEW

**Comment by chriscool** [comment]
Yeah, this LGTM. Thanks!

**Comment by anarcat** [comment]
So I forgot to update this PR unfortunately, but there are two more tests missing that we're using in the Git-Mediawiki project, as you can see in our final commit: https://github.com/anarcat/Git-Mediawiki/commit/06694fda008a1e22dc4b3d014e13d27031663006#diff-1a3e5e27180742ac2f268d7df5e0d30bR99

Those are `test_path_is_missing` and `test_i18ngrep`, but there are probably a bunch more missing... (How) do you keep track of the updates from the git side?

**Comment by chriscool** [comment]
Updates from the Git side are made when someone needs something that has already been implemented on the Git side. So I would suggest sending another commit with the 2 functions that are missing.

**Comment by anarcat** [comment]
okay, will do thanks.

**Comment by ahmad1280** [comment]
> _ No description provided. _

#132

**Pull request merged**
