### PR TITLE
Add vim syntax file

### PR DESCRIPTION
**Pull request by felipec**
It's annoying to see all the bodies of unit tests in the same color.

This syntax file is not perfect, but does a good enough job.

### CODE REVIEW

**Comment by chriscool** [comment]
Thanks @felipec !

**Comment by sergeyklay** [comment]
@felipec Could you please share some screenshots with before and after looks?

**Comment by felipec** [comment]
> @sergeyklay The before is just `ft=text`, the after was shared in the mailing list:

[sharness screenshot](https://i.imgur.com/qDgvjtu.png).

**Comment by sergeyklay** [comment]
Thank you. Well, we'll need to provide Emacs support too :)

**Pull request merged**
