### PR TITLE
Move functions into lib-sharness/functions.sh

### PR DESCRIPTION
**Pull request by chriscool**
This makes it easier to maintain Sharness, as it is more
compatible with the Git test suite and less code is in
"sharness.sh".

The downside is that it is not possible anymore to install
Sharness by just copying "sharness.sh".

### CODE REVIEW

**Comment by chriscool** [comment]
Ok, so there is an issue with variables that appear unused.

And I think another issue is that some functions, that are not public, should not be in "functions.sh".

**Comment by chriscool** [comment]
Other issues related to the Makefile:

- aggregate-results.sh should probably be moved into lib-sharness
- the "install" target in the Makefile should install the whole lib-sharness directory

**Comment by chriscool** [comment]
I think I fixed everything.

And I think I will merge this in a few weeks as I want to add more things into the new `lib-sharness` directory.

**Comment by chriscool** [comment]
This might be a bit disruptive when Sharness is not installed in the same directory as the test scripts. In this case the best is perhaps to set `SHARNESS_TEST_SRCDIR` somewhere properly, then to export it and to source `sharness.sh` in the test files using something like:

```
. "$SHARNESS_TEST_SRCDIR/sharness.sh"
```

(See also how it's done in [test/simple.t](test/simple.t).)

Another way would be to have symlinks to both `sharness.sh` and `lib-sharness` in the test scripts.

**Comment by hsanjuan** [comment]
Huge downside

**Comment by felipec** [comment]
@hsanjuan Actually I partially reverted some of those changes. Moving back `test_expect_*` and `test_done`.

Doing that `lib-sharness` becomes **optional**. Although it contains useful functions, not all project would need to import it, and of course you can selectively copy the functions you need as well.

See c5395ee.

**Pull request merged**
